CREATE DATABASE myDB; -- Create a database

-- OTHER USEFUL COMMANDS ARE WRITTEN AS COMMENT FOR FUNDAMENTAL LEARNING HERE

/* USE mydb; -- Uses database mydb
DROP DATABASE mydb ; -- Delets a data base 
ALTER DATABASE myDB READ ONLY=1; -- KEEPS DATABASE TO NON EDITABLE
ALTER DATABASE myDB READ ONLY=0; -- KEEPS DATABASE TO  EDITABLE
*/ 