# command is used to create table
/* USE mydb;
CREATE TABLE PLAYERS (
     PLAYER_ID int,
     FIRST_NAME varchar(30),
     LAST_NAME varchar(20),
     SPORTS varchar(20),
     DEBUT_DATE DATE,
     PAY_PER_GAME DECIMAL(5,2) -- (5,2) MEANS MAXIMUM 5 DIGITS BEFORE DECIMAL AND 2 DIGIS AFTER DECIMAL
); */

--  SELECT*FROM players; SELECTS THE TABLE players
--  RENAME TABLE players to athelets; RENAME TABLE NAME
--  DROP TABLE players; TO DELETE TABLE
--  ALTER TABLE employees; TO SELECT A TABLE TO CHANGE 
--  ADD phone_number VARCHAR(15); ADDS PHONE NUMBER COLUMN IN THE SELETED TABLE BY ALTER STATEMENT
--  RENAME COLUMN phone_number to email; RENAME THE COLUMN OF SELECTED TABLE
--  M0DIFY COLUMN email VARCHAR(100); USED TO MODIFY DATATYPE
--  AFTER LAST_NAME;  SHIFTS SELECTED TABLES COLUMN TO AFTER COLUMN LAST NAME
--  FIRST; SHIFTS SELECTED TABLES COLUMN TO FIRST
--  DROP COLUMN email; DELETS COLUMN EMAIL



