-- SET SQL_SAFE_UPDATES = 0;  (TO INDICATE SAFE UPDATE)
UPDATE players 
set PAY_PER_GAME= 20.25,
    DEBUT_DATE="2024-10-11" 
where PLAYER_ID = 1;
select*FROM players;

-- DELETE FROM players -- (DELETE ALL ROWS FROM TABLE)
-- WHERE PLAYER_ID=1 (DELETE THE ROWS WHICH SATISFY THE CONDITION)
