 -- UNIQUE CONSTRAINT 
 
 CREATE TABLE PRODUCT(
      PRODUCT_ID INT,
      PRODUCT_NAME VARCHAR(25) UNIQUE,-- ONLY UNIQUE PRODUCT NAME CAN BE INPUTED
      PRICE DECIMAL (4,2)
 );
 /*
 ALTER TABLE PRODUCT
 ADD CONSTRAINT
 UNIQUE(PRODUCT_NAME)
 */ -- TO MAKE UNIQUE AFTER CREATING TABLE