-- UNIQUE CONSTRAINT 
 
 CREATE TABLE PRODUCT(
      PRODUCT_ID INT,
      PRODUCT_NAME VARCHAR(25),
      PRICE DECIMAL (4,2) NOT NULL -- NULL VALUE CANNOT BE INPUTED
 );
 /*
 ALTER TABLE PRODUCT
 MODIFY PRICE DECIMAL(4,2) NOT NULL;
 */ -- TO MAKE NOT NULL AFTER CREATING TABLE