/* create table players(
   PLAYER_ID INT,
   FIRST_NAME VARCHAR(30),
   LAST_NAME VARCHAR(20),
   SPORTS VARCHAR(20),
   DEUBUT_DATE DATE,
   PAY_PER_GAME DECIMAL(5,2)
   CONSTRAINT PAY_PER_GAME CHECK(PAY_PER_GAME>=10.00)
   --  CONSTRAINT PAY_PER_GAME CHECK(PAY_PER_GAME>=10)
   ); */

/*
ALTER TABLE PLAYERS
ADD CONSTARINT PAY_PER_GAME CHECK(PAY_PER_GAME>=10)
*/

-- Adds a CHECK constraint to ensure PAY_PER_GAME is always 10 or more IF IT IS NOT CREATED AT BEGINNING
-- WHEN WE USES THIS CHECK COONSTRAINT THE DATA WHICH DOES NOT SATISFY THIS CONDITION CANNOT BE INSERTED
