-- DEFAULT constraint automatically assigns a specified value to a column when no value is provided during an INSERT operation.

/* WHILE CRAETING A TABLE
 CREATE TABLE PRODUCT(
      PRODUCT_ID INT,
      PRODUCT_NAME VARCHAR(25),
      PRICE DECIMAL (4,2) DEFAULT 0
      */  -- MAKES DEFAULT AVLUEE TO 0
      
-- AFTER CREATING TABLE

-- ALTER TABLE PRODUCT 
-- ALTER PRICE SET DEFAULT 0

-- DATETIME DEFAULT NOW -- THIS COMMANDS HELPS TO STORE TRANSACTION DATE AND TIME OR ANY TASK DATE TIME BY DEFAULT