-- PRIMARY KEY: UNIQUE IDENTIFIER VALUE MUST BE UNIQUE AND NON NULL
-- TABLE CAN ONLY HAVE 1 PRIMARY KEY CONSTARINT

-- CREATE TABLE WITH PRIMARY KEY

CREATE TABLE TRANSACTION(
     TRANS_ID INT PRIMARY KEY,
     AMOUNT DECIMAL (8,2)
     );

-- PRIMARY KEY IN ALREADY CREATED TABLE

ALTER TABLE TRANSACTION
ADD CONSTRAINT 
primary key(TRANS_ID);